import type { Metadata } from "next";
import { Orbitron, Exo } from "next/font/google";
import "./globals.css";
import Layout from "@/components/layout/Layout";

const orbitron = Orbitron({
    variable: "--font-orbitron",
    subsets: ["latin"],
});

const exo = Exo({
    variable: "--font-exo",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${orbitron.variable} ${exo.variable} antialiased`}
            >
                <Layout>{children}</Layout>
            </body>
        </html>
    );
}
